services:
  - type: web
    name: cauliflare-backend
    env: docker
    dockerfilePath: ./Dockerfile
    rootDir: backend
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /api/health
